--- 
- hosts: k8s
  
  vars_files: 
    - vars/main.yml


  pre_tasks: 
    - name: Copy Flannel manifest tailored for Vagrant.
      copy: 
        src: files/manifests/kube-flannel-vagrant.yml 
        dest: "~/kube-flannel-vagrant.yml"

  roles: 
    - role: geerlingguy.swap
      tags: ['swap', 'kubernetes']

    - role: geerlingguy.docker
      tags: ['docker']

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']
  
  tasks: 
    - name: Copy k8-files into master VM
      copy: 
        src: "{{ item }}"
        dest: /root/
      with_fileglob: files/*.yaml
      delegate_to: k8s-master
      tags: copy-files