apiVersion: v1
kind: Pod
metadata:
  name: nginx
  creationTimestamp: null
  labels:
    name: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 8080
  nodeName: node2